# Site settings
title: Ethereal
subtitle: by HTML5 Up
description: >- # this means to ignore newlines until "baseurl:"
  This is Ethereal, my latest, greatest, and quite possibly most unique template for HTML5 UP.
  Since releasing Parallelism 3-4 years ago (!!!), I've been dying to do another side-scrolling
  template with more in the way of flexibility/customization potential. The result is this template,
  Ethereal, which combines a robust side-scrolling framework of my own creation (with various
  "scroll-assist" features like drag/momentum scrolling, keyboard shortcuts, etc.) with a unique
  look and feel, a lightbox gallery, tons of customization options, and, of course, full
  responsiveness. Hope you dig it :)

# Contact information
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555
email: youremailaddress@gmail.com

# Social settings
500px:
facebook:
  url: "https://github.com/apehex"
  label: "facebook.com/untitled"
github:
  url: "https://github.com/apehex"
  label: "github.com/untitled"
gitlab:
instagram:
  url: "https://github.com/apehex"
  label: "@untitled-tld"
linkedin:
medium:
  url: "https://github.com/apehex"
  label: "medium.com/untitled"
pinterest:
slack:
snapchat:
  url: "https://github.com/apehex"
  label: "@untitled-tld"
twitter:
  url: "https://github.com/apehex"
  label: "@untitled-tld"

# Optional elements
logo:
  url: /assets/images/logo.svg
  alt: logo
favicon:
  url: /assets/images/favicon.ico
  alt: favicon
legal_terms:
  url: /en/legal-terms
privacy_policy:
  url: /en/privacy-policy

# Privacy notice
hosting_third_party: github

# Collections
collections:
  demo:
    output: false
  home:
    output: false
  privacy-policy:
    output: false
  redirects:
    output: true
    permalink: /:path/

# Default settings
defaults:
  -
    scope:
      type: "redirects"
    values:
      layout: "redirect"
      lang: "x-default"
  -
    scope:
      path: ""
    values:
      menu: default
  -
    scope:
      path: "en"
    values:
      lang: "en"
  -
    scope:
      path: "fr"
    values:
      lang: "fr"

# Build settings
permalink: pretty
markdown: kramdown
sass:
  style: compressed

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://apehex.github.io/jekyll-theme-ethereal" # the base hostname & protocol for your site, e.g. http://example.com
author: HTML5 Up
copyright:
  holder: Untitled
  license: CC0

# Exclude from processing
